version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
  mnemonic: shell bacon ozone excess need gesture casino warrior all excuse bicycle slim combine interest crisp describe fence delay federal behind biology real type fence
- name: bob
  coins:
  - 10000token
  - 100000000stake
  mnemonic: robot sock leopard install fit oyster agent because exist issue orient add jungle mask decorate focus alter uncover burger deputy damage property throw gloom
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
